Repository ES2-UFPI/AppCut, pull requests merged in 2022-05, with the labels that each got.

#15 [AC-2]: Adicionando gem active storage para upload de imagens e formu…
  app/assets/stylesheets/professional_profiles.scss
  app/controllers/professional_profiles_controller.rb
  app/helpers/professional_profiles_helper.rb
  app/models/professional_profile.rb
  app/views/professional_profiles/_form.html.erb
  app/views/professional_profiles/edit.html.erb
  app/views/professional_profiles/show.html.erb
  config/routes.rb
  db/migrate/20220502014939_create_active_storage_tables.active_storage.rb
  test/controllers/professional_profiles_controller_test.rb
Labels: documentation

#14 Criação e edição de Agendas
  app/assets/stylesheets/agendas.scss
  app/controllers/agendas_controller.rb
  app/helpers/agendas_helper.rb
  app/models/agenda.rb
  app/views/agendas/_form.html.erb
  app/views/agendas/edit.html.erb
  app/views/agendas/new.html.erb
  app/views/agendas/show.html.erb
  config/routes.rb
  db/migrate/20220502022123_create_agendas.rb
  db/schema.rb
  test/controllers/agendas_controller_test.rb
  test/fixtures/agendas.yml
  test/models/agenda_test.rb
Labels: bug, duplicate

#16 [AC-2]: subindo alterações
  app/assets/stylesheets/profissional_profiles.scss
  app/controllers/professional_profiles_controller.rb
  app/controllers/profissional_profiles_controller.rb
  app/helpers/profissional_profiles_helper.rb
  app/views/professional_profiles/_form.html.erb
  app/views/professional_profiles/index.html.erb
  test/controllers/profissional_profiles_controller_test.rb
  test/fixtures/professional_profiles.yml
Labels: documentation

#20 [AC-2]: Adicionando Pundit para politica e controle de acesso
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/professional_profiles_controller.rb
  app/policies/application_policy.rb
  app/policies/professional_profile_policy.rb
  app/views/home/index.html.erb
  app/views/professional_profiles/index.html.erb
  app/views/professional_profiles/show.html.erb
  test/policies/professinal_profile_policy_test.rb
Labels: enhancement

#22 Home page feita, paginação com kaminari e ajustes no perfil profissonal
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/controllers/home_controller.rb
  app/controllers/professional_profiles_controller.rb
  app/javascript/packs/application.js
  app/models/professional_profile.rb
  app/policies/professional_profile_policy.rb
  app/views/home/index.html.erb
  app/views/kaminari/_first_page.html.erb
  app/views/kaminari/_gap.html.erb
  app/views/kaminari/_last_page.html.erb
  app/views/kaminari/_next_page.html.erb
  app/views/kaminari/_page.html.erb
  app/views/kaminari/_paginator.html.erb
  app/views/kaminari/_prev_page.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/professional_profiles/_card.html.erb
  app/views/professional_profiles/_form.html.erb
Labels: documentation

#23 [AC-6]: Correção da policy de Professional Profile e adição de botão para agendamento
  app/assets/stylesheets/custom.css
  app/policies/professional_profile_policy.rb
  app/policies/user_policy.rb
  app/views/layouts/application.html.erb
  app/views/professional_profiles/_form.html.erb
  app/views/professional_profiles/edit.html.erb
  app/views/professional_profiles/show.html.erb
Labels: documentation

#26 Ac 10
  app/views/agendas/_modal_agenda.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
Labels: enhancement

#27 [AC-9]: Adicionando a funcionalidade de avaliações para uma barbearia como comentário e visualização aos usuários da mesma
  app/assets/stylesheets/custom.css
  app/assets/stylesheets/rates.scss
  app/controllers/professional_profiles_controller.rb
  app/controllers/rates_controller.rb
  app/helpers/rates_helper.rb
  app/models/professional_profile.rb
  app/models/rate.rb
  app/views/agendas/_form.html.erb
  app/views/professional_profiles/_level_menu.html.erb
  app/views/professional_profiles/show.html.erb
  app/views/rates/_form.html.erb
  app/views/rates/_rate.html.erb
  app/views/rates/new.html.erb
  config/environment.rb
  config/routes.rb
  db/migrate/20220509020049_create_rates.rb
  db/schema.rb
  test/controllers/rates_controller_test.rb
  test/fixtures/rates.yml
  test/models/rate_test.rb
Labels: enhancement

#28 Ac 8
  app/controllers/addresses_controller.rb
  app/controllers/agendas_controller.rb
  app/controllers/haircut_schedules_controller.rb
  app/controllers/home_controller.rb
  app/controllers/professional_profiles_controller.rb
  app/controllers/rates_controller.rb
  app/helpers/agendas_helper.rb
  app/helpers/haircut_schedules_helper.rb
  app/policies/agenda_policy.rb
  app/policies/haircut_schedule_policy.rb
  app/views/agendas/_form.html.erb
  app/views/agendas/_modal_agenda.html.erb
  app/views/agendas/index.html.erb
  app/views/agendas/show.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/haircut_schedules/_form.html.erb
  app/views/haircut_schedules/edit.html.erb
  app/views/haircut_schedules/new.html.erb
  app/views/haircut_schedules/show.html.erb
  app/views/home/index.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/professional_profiles/_form.html.erb
  app/views/professional_profiles/_level_menu.html.erb
  app/views/professional_profiles/edit.html.erb
  app/views/professional_profiles/show.html.erb
  config/application.rb
  config/routes.rb
Labels: enhancement

#31 Alteração na mensagem de erro da view edição de endereços
  app/views/addresses/index.html.erb
Labels: enhancement

#32 [AC-9]: Corrigindo erro na view show de professional profile e redimensionando imagens dos cards
  app/assets/stylesheets/custom.css
  app/views/professional_profiles/show.html.erb
Labels: bug
